### ISSUE TITLE
Syntax error unexpected token

### ISSUE THREAD

**Issue by Jborn4christ** [apexad/homebridge-garagedoor-command#17]
Getting close to figuring out how to configure this. Think I’m almost there with my Aladdin Connect. Any help figuring this out would be much appreciated. I am more than happy to throw a few bucks your way. Now just getting an error that reads:

[6/19/2019, 8:56:27 PM] [Garage Door] Error: Command failed: node C:/Users/Chambers/AppData/Roaming/npm/node_modules/garage-control/state.js
C:\Users\Chambers\AppData\Roaming\npm\node_modules\node-aladdin-connect-garage-door-master\example\node_modules\node-aladdin-connect-garage-door\index.js:36
modules.export = (user, password, action, callback, deviceNumber = 0, doorNumber = 1) {
                                                                                      ^

SyntaxError: Unexpected token {
    at Module._compile (internal/modules/cjs/loader.js:718:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:785:10)
    at Module.load (internal/modules/cjs/loader.js:641:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Module.require (internal/modules/cjs/loader.js:681:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (C:\Users\Chambers\AppData\Roaming\npm\node_modules\node-aladdin-connect-garage-door-master\example\state.js:1:25)
    at Module._compile (internal/modules/cjs/loader.js:774:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:785:10)
    at Module.load (internal/modules/cjs/loader.js:641:32)

    at ChildProcess.exithandler (child_process.js:290:12)
    at ChildProcess.emit (events.js:200:13)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5) {
  killed: false,
  code: 1,
  signal: null,
  cmd: 'node ' +
    'C:/Users/Chambers/AppData/Roaming/npm/node_modules/garage-control/state.js

**Comment by apexad** [comment]
This appears to be a Windows 10 related issue.
Please verify you can run node via command line.
