### ISSUE TITLE
update crash homebridge

### ISSUE THREAD

**Issue by aecom** [apexad/homebridge-garagedoor-command#28]
[4/2/2021, 19:17:15] [Garage Door] Initializing GarageCommand accessory...
[4/2/2021, 19:17:16] TypeError: accessory.pollSate is not a function
    at GarageCmdAccessory.pollState (/usr/lib/node_modules/homebridge-garagedoor-command/index.js:98:47)
    at GarageCmdAccessory.getServices (/usr/lib/node_modules/homebridge-garagedoor-command/index.js:111:33)
    at BridgeService.createHAPAccessory (/usr/lib/node_modules/homebridge/src/bridgeService.ts:456:41)
    at /usr/lib/node_modules/homebridge/src/server.ts:353:44
    at Array.forEach (<anonymous>)
    at Server.loadAccessories (/usr/lib/node_modules/homebridge/src/server.ts:270:29)
    at Server.start (/usr/lib/node_modules/homebridge/src/server.ts:162:12)
[4/2/2021, 19:17:16] Got SIGTERM, shutting down Homebridge...
[4/2/2021, 19:17:16] TypeError: accessory.getCharacteristic is not a function
    at /usr/lib/node_modules/homebridge-garagedoor-command/index.js:94:15
    at ChildProcess.exithandler (child_process.js:294:7)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Socket.<anonymous> (internal/child_process.js:443:11)
    at Socket.emit (events.js:315:20)
    at Pipe.<anonymous> (net.js:674:12)
[4/2/2021, 19:17:16] [RiscoAlarm] Sesion expired, relogin...
[4/2/2021, 19:17:21] [HB Supervisor] Homebridge Process Ended. Code: 143, Signal: null
[4/2/2021, 19:17:26] [HB Supervisor] Restarting Homebridge...
[4/2/2021, 19:17:26] [HB Supervisor] Starting Homebridge with extra flags: -

**Comment by apexad** [comment]
fixed in 0.5.1
